// Smoke test for leader role
// Run with: node tests/leader.test.mjs
//
// Verifies the leader source implements spawn polling, multi-harness
// tmux management, and proper daemon API integration.

import * as assert from "node:assert";
import * as fs from "node:fs";
import * as path from "node:path";

const src = fs.readFileSync(
  path.join(import.meta.dirname, "../src/leader.ts"),
  "utf-8"
);

let passed = 0;
let failed = 0;

function test(label, fn) {
  try {
    fn();
    console.log(`  ✓ ${label}`);
    passed++;
  } catch (e) {
    console.log(`  ✗ ${label}: ${e.message}`);
    failed++;
  }
}

console.log("Leader role source checks:");

// ─── Exports and structure ───────────────────────────────────────

test("exports setupLeader function", () => {
  assert.ok(src.includes("export async function setupLeader("));
});

test("imports DaemonClient", () => {
  assert.ok(src.includes('import type { DaemonClient }'));
});

test("imports registerLeaderTools", () => {
  assert.ok(src.includes('import { registerLeaderTools }'));
});

// ─── Daemon registration ─────────────────────────────────────────

test("registers with daemon on startup", () => {
  assert.ok(src.includes('client.register({ name: "leader", directory: cwd })'));
});

test("deregisters on session_shutdown", () => {
  assert.ok(src.includes("client.deregister()"));
});

test("gets host config from daemon", () => {
  assert.ok(src.includes("client.getHostConfig()"));
});

test("gets daemon config for harness templates", () => {
  assert.ok(src.includes("client.getConfig()"));
});

// Regression: the leader once resolved tmuxSession only once at startup. If
// the daemon was unreachable at that moment, the hardcoded fallback session
// ("pi-pizza-team") was cached forever and spawns landed in the wrong tmux
// session even after the daemon came back. Config sync must be retryable.
test("config sync is a retryable function", () => {
  assert.ok(src.includes("async function syncDaemonConfig()"));
  assert.ok(src.includes("configSynced = true"));
});

test("heartbeat retries config sync and re-registers when dismissed", () => {
  assert.ok(src.includes("if (res.dismissed)"));
  assert.ok(/if \(!configSynced\) \{\s*\n\s*try \{ await syncDaemonConfig\(\); \}/.test(src));
});

test("directive poll refuses to dispatch before config sync", () => {
  assert.ok(src.includes("if (!configSynced) await syncDaemonConfig();"));
});

// ─── Spawn request polling ───────────────────────────────────────

test("polls the single leader-directive queue every 5s", () => {
  assert.ok(src.includes("SPAWN_POLL_INTERVAL_MS = 5000"));
  assert.ok(src.includes("client.getLeaderDirectives()"));
});

test("completes directives after realizing them", () => {
  assert.ok(src.includes("client.completeLeaderDirective(directive.id)"));
  assert.ok(src.includes("dispatchDirective("));
});

test("spawned agent names come from the daemon with a timestamp fallback", () => {
  // Names are generated by the daemon via a spawn directive; the leader falls
  // back to a timestamped name only if the directive omits one.
  assert.ok(src.includes("res.directive?.params?.name"));
  assert.ok(src.includes("`agent-${Date.now()}`"));
});

// ─── Multi-harness support ───────────────────────────────────────

test("has default harness templates for pi and pi-assistant", () => {
  assert.ok(src.includes('"pi-assistant"'));
  assert.ok(src.includes("pi:"));
});

test("pi template uses -a --ppt-worker --ppt-daemon --ppt-name", () => {
  assert.ok(src.includes("pi -a --ppt-worker --ppt-daemon={url} --ppt-name={name}"));
});

test("pi-assistant template uses -a --ppt-assistant and threads {name} (daemon-owned identity)", () => {
  // The assistant is a distinct role but not a distinct identity: the daemon
  // assigns the reserved "assistant" name, so the template threads {name}
  // rather than hardcoding it. This keeps tmux window == registered name.
  assert.ok(src.includes("pi -a --ppt-assistant --ppt-daemon={url} --ppt-name={name}"));
  assert.ok(!src.includes("--ppt-name=assistant"));
});

test("pi harness templates auto-approve project trust", () => {
  // -a (--approve) lets a spawned teammate trust its cwd non-interactively so
  // it doesn't block on pi's "Trust project folder?" prompt.
  assert.ok(src.includes('pi: "pi -a '));
  assert.ok(src.includes('"pi-assistant": "pi -a '));
});

test("spawnAgent resolves template placeholders", () => {
  assert.ok(src.includes(".replace(/\\{name\\}/g,"));
  assert.ok(src.includes(".replace(/\\{url\\}/g,"));
  assert.ok(src.includes(".replace(/\\{cwd\\}/g,"));
  assert.ok(src.includes(".replace(/\\{workArgs\\}/g,"));
});

test("loads custom harness templates from daemon config", () => {
  assert.ok(src.includes("daemonConfig.harnessCommands"));
});

// ─── tmux management ─────────────────────────────────────────────

test("has ensureSession function", () => {
  assert.ok(src.includes("function ensureSession("));
});

test("has spawnAgent function", () => {
  assert.ok(src.includes("function spawnAgent("));
});

test("has dismissAgent function", () => {
  assert.ok(src.includes("function dismissAgent("));
});

test("has listWindows function", () => {
  assert.ok(src.includes("function listWindows("));
});

test("spawnAgent skips creating a window when one with the name already exists", () => {
  // Guards against retried spawn directives piling up duplicate tmux windows,
  // since tmux does not enforce unique window names.
  assert.ok(src.includes("listWindows(session, execSync).includes(name)"));
});

test("spawnAgent validates the cwd before touching tmux", () => {
  // A bad/half-typed cwd must fail before any window is created.
  assert.ok(src.includes("validateSpawnCwd(agentCwd)"));
  assert.ok(src.includes("if (cwdError) throw new Error(cwdError)"));
  const spawnStart = src.indexOf("function spawnAgent(");
  const validateIdx = src.indexOf("validateSpawnCwd(agentCwd)", spawnStart);
  const firstNewWindow = src.indexOf("new-window", spawnStart);
  assert.ok(validateIdx > -1 && validateIdx < firstNewWindow);
});

test("validateSpawnCwd rejects missing paths and non-directories", () => {
  assert.ok(src.includes("function validateSpawnCwd("));
  assert.ok(src.includes("Working directory does not exist"));
  assert.ok(src.includes("Not a directory"));
});

test("ensurePermissiveConfig failure does not abort the spawn", () => {
  // The permissive config is a convenience; a write failure (e.g. read-only
  // cwd) is caught and logged rather than throwing.
  assert.ok(src.includes("Could not write permissive config"));
});

test("unrealizable directives are marked failed, not retried forever", () => {
  assert.ok(src.includes("client.failLeaderDirective(directive.id)"));
});

test("/ppt-spawn validates the cwd before creating a directive", () => {
  assert.ok(src.includes('cmdCtx.ui.notify(`Cannot spawn: ${cwdError}`'));
});

test("has ensurePermissiveConfig function", () => {
  assert.ok(src.includes("function ensurePermissiveConfig("));
});

test("only sets up permission config for pi harness", () => {
  assert.ok(src.includes('if (harness === "pi")'));
  assert.ok(src.includes("ensurePermissiveConfig(agentCwd)"));
});

test("dismissAgent sends Ctrl+C then kills the window", () => {
  assert.ok(src.includes("C-c"));
  assert.ok(src.includes("kill-window"));
});

// ─── Slash commands ──────────────────────────────────────────────

test("registers /ppt-spawn command", () => {
  assert.ok(src.includes('"ppt-spawn"'));
});

test("registers /ppt-dismiss command", () => {
  assert.ok(src.includes('"ppt-dismiss"'));
});

test("registers /ppt-hop command", () => {
  assert.ok(src.includes('"ppt-hop"'));
});

test("registers /ppt-status command", () => {
  assert.ok(src.includes('"ppt-status"'));
});

test("/ppt-status fetches from daemon", () => {
  assert.ok(src.includes("client.getStatus()"));
});

test("/ppt-status shows tmux windows", () => {
  assert.ok(src.includes("listWindows(tmuxSession"));
});

// ─── Widget ──────────────────────────────────────────────────────

test("updates widget periodically", () => {
  assert.ok(src.includes("WIDGET_UPDATE_INTERVAL_MS"));
  assert.ok(src.includes("setWidget"));
});

test("widget shows task progress", () => {
  assert.ok(src.includes("tasks done"));
});

test("widget shows task progress", () => {
  assert.ok(src.includes("tasks done"));
  assert.ok(src.includes("setWidget"));
});

// ─── Shell safety ────────────────────────────────────────────────

test("has shellSafe function", () => {
  assert.ok(src.includes("function shellSafe("));
});

test("shellSafe removes dangerous characters", () => {
  assert.ok(src.includes("[^a-zA-Z0-9._~/:@-]"));
});

// ─── No server-side deps ─────────────────────────────────────────

test("does not import better-sqlite3 or hono", () => {
  assert.ok(!src.includes("better-sqlite3"));
  assert.ok(!src.includes("hono"));
});

test("does not import Store", () => {
  assert.ok(!src.includes("Store"));
});

test("delivers reset-session intent as Pi's /new keystrokes", () => {
  assert.ok(src.includes("deliverAgentCommand"));
  assert.ok(src.includes('"reset-session": "/new"'));
  assert.ok(src.includes("client.getLeaderDirectives()"));
  assert.ok(src.includes("client.completeLeaderDirective("));
});

test("passes tmux session/window to spawned agents", () => {
  assert.ok(src.includes("--ppt-tmux-session={session} --ppt-tmux-window={window}"));
  assert.ok(src.includes(".replace(/\\{window\\}/g,"));
});

console.log(`\n${passed} passed, ${failed} failed`);
process.exit(failed > 0 ? 1 : 0);
